### PR TITLE
Temp fix for serialization stack overflow.

### LINKED ISSUE #6: Serialization stack overflow on Merge calls
Kryo Serialization issue involving the serialization of objects in the recursive call of `SetTheoryWithSingleCollection`.

### PR DESCRIPTION
**Pull request by devin-petersohn**
Temporarily resolves #6

### CODE REVIEW

File: lime-core/src/main/scala/org/bdgenomics/lime/serialization/LimeKryoRegistrator.scala [hunk 1]
```diff
@@ -9,8 +9,22 @@ class LimeKryoRegistrator extends KryoRegistrator {
   private val akr = new ADAMKryoRegistrator()
 
   override def registerClasses(kryo: Kryo) {
+    kryo.register(classOf[scala.Array[org.bdgenomics.adam.models.ReferenceRegion]])
```
Comment (devin-petersohn) [inline lime-core/src/main/scala/org/bdgenomics/lime/serialization/LimeKryoRegistrator.scala]: Unfortunately, right now we are having to individually register each class, and there is a problem using ADAM's kryo serialization.
